print("I'm learning Git merge conflicts")
name = input('Please enter your name:')
last_name = input('Please enter your last name:')
print(f"Hi, {name} {last_name}!")
nick = input('Please enter your nickname')
print(f"Hi, {nick}!")
